# yaml-language-server: $schema=../../schemas/canvas-course.schema.json
# Use 2 spaces for indentation. Do not use tabs.

courseId: 101

expected:
  details:
    name: "Example 1"
    courseCode: "Example 1"
    restrictEnrollmentsToCourseDates: false
    timeZone: "Europe/London"
    startDateRequired: false
    endDateRequired: false

  settings:
    discussionsAllowed: false
    restrictFutureView: true
    restrictPastView: true
